spring.application.name: dead-code-detector
spring.boot.admin.client.enabled: false
server.error.whitelabel.enabled: false

endpoints:
  health:
    sensitive: false
  restart:
    enabled: false
  shutdown:
    enabled: false

command.line.timeout: 12000000

---
spring:
    profiles: local

data.dir: ./data
scitools.dir: /Users/dgladyshev/scitools/bin/macosx #set to you local scitools path

---
spring:
    profiles: test
data.dir: ./data
scitools.dir: /scitools/bin/linux64

---
spring:
    profiles: dev

data.dir: /data
scitools.dir: /scitools/bin/linux64

