spring.application.name: dead-code-detector
spring.boot.admin.client.enabled: false
server.error.whitelabel.enabled: false

endpoints:
  health:
    sensitive: false
  restart:
    enabled: false
  shutdown:
    enabled: false

data.dir: ./data
scitools.dir: /Users/dgladyshev/scitools/bin/macosx
max.stored.inspections: 100000


