spring.application.name: dead-code-detector
spring.boot.admin.client.enabled: false
server.error.whitelabel.enabled: false

endpoints:
  health:
    sensitive: false
  restart:
    enabled: false
  shutdown:
    enabled: false

---
spring:
    profiles: local

data.dir: ./data
scitools.dir: /Users/dgladyshev/scitools/bin/macosx #set to you local scitools path

---
spring:
    profiles: dev

data.dir: ./data
scitools.dir: /scitools

---
spring:
    profiles: stage

url: http://some_url #TODO
---

spring:
    profiles: prod

url: http://some_url #TODO